title: 枕边书
url: "https://zhenbianshu.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://github.com/zhenbianshu"
footer_text: "be in awe"

sass:
    style: compressed
    sass_dir: _sass
