name: 枕边书
description: 常怀敬畏之心。
url: https://zhenbianshu.github.io
baseurl: ''
github: 'zhenbianshu'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# 评论
comments: true
disqus: 'zhenbianshu'

permalink: /:year/:month/:title.html
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md']


# 文章相关配置
article:
  copyright: 转载随意，请注明来源地址：<a href="https://zhenbianshu.github.io">https://zhenbianshu.github.io</a> ，文章持续修订。
  summary: 关于本文有什么疑问可以在下面留言交流，如果您觉得本文对您有帮助，欢迎关注我的 <a href="https://weibo.com/u/5715965217">微博</a> 或  <a href="https://github.com/zhenbianshu/">GitHub</a> 。
